name: DEV NOTE
description: 'Jekyll Bulma Theme, Bulma.io CSS Framework Jekyll Template for Developers'
baseurl: ''
url: http://deasik.github.io
social:
    github: deasik
    email: ids861207@gmail.com
    facebook:
    twitter:
    instagram:
    tumblr:
author:
    name: Deasik Kim
    bio: 'Spring Developer, React Developer'
    email: ids861207@gmail.com
    image: /assets/images/author.jpg
    github: deasik
    facebook:
    twitter:
    instagram:
    tumblr:
    show_on_post: true
permalink: /:categories/:title/
sass:
    style: compressed
paginate: 5
paginate_path: '/:num/'
markdown: kramdown

plugins:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-gist

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - CNAME
    - vendor
