name: DEV NOTE
description: 'Study Notes of a Developer.'
baseurl: ''
url: http://ds-derek.github.io
social:
    github: ds-derek
    email: ids861207@gmail.com
    facebook:
    twitter:
    instagram:
    tumblr:
author:
    name: Deasik Derek Kim
    bio: 'Spring Developer, React Developer'
    email: ids861207@gmail.com
    image: /assets/images/author-ds.png
    github: ds-derek
    facebook:
    twitter:
    instagram:
    tumblr:
    show_on_post: true
permalink: /:categories/:title/
sass:
    style: compressed
paginate: 5
paginate_path: '/:num/'
markdown: kramdown

plugins:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-gist

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - CNAME
    - vendor
